# TODO use a specific style for each project, change slowly, then remove this file.
# E.g.: python36-nitpick-style.toml, frontend-nitpick-style.toml, etc.

# Default nitpick style file for EatFirst
# See https://github.com/andreoliwa/nitpick

[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
    "styles/python36",
    "styles/poetry",
    "styles/absent-files",
    "styles/pre-commit/main",
    "styles/pre-commit/general",
    "styles/pre-commit/python",
    "styles/pre-commit/bash",
    "styles/pre-commit/commitlint",
    "styles/black",
    "styles/flake8",
    "styles/pylint",
    "styles/isort",
    "styles/mypy",
    "styles/pytest",
    "styles/ipython",
]

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude", "isort.skip", "isort.known_first_party"]
