["pyproject.toml".tool.black]
line-length = 120

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.3b0]
"""
